spring:
  datasource:
    url: jdbc:h2:D:\nonatorw\fiap-35scj-cervejaria-batch-tasklet\db\fiapcervejariabatch;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
file:
  path: D:\nonatorw\Spring\Spring.7z